{NAMA      : Haldi Alamsyah
NPM        : 20.14.1.0036
KELOMPOK   : Kelompok 6
KODE SOAL  : A  }


PROGRAM BIODATA;
USES CRT;
VAR
NAMA, NPM, KELAMIN, ALAMAT, KONTAK : STRING;

BEGIN
CLRSCR;
WRITELN('PROGRAM BIODATA');
WRITE('MASUKAN NAMA ANDA: ');
READLN(NAMA)   ;
WRITE('MASUKAN NPM ANDA: ');
READLN(NPM)    ;
WRITE('MASUKAN KELAMIN: ');
READLN(KELAMIN);
WRITE('MASUKAN ALAMAT ANDA: ');
READLN(ALAMAT) ;
WRITE('MASUKAN KONTAK ANDA: ');
READLN(KONTAK) ;
WRITELN('================================');
WRITELN('================================');
WRITELN('================================');

WRITELN('PROGRAM BIODATA');
WRITELN('NAMA SAYA ADALAH '          ,NAMA);
WRITELN('NPM SAYA ADALAH '           ,NPM);
WRITELN('JENIS KELAMIN SAYA ADALAH ' ,KELAMIN);
WRITELN('ALAMAT SAYA DI '            ,ALAMAT);
WRITELN('KONTAK SAYA '               ,KONTAK);
READLN;
END.


